layout_spectrum: 0.5828056898899376
typography_spectrum: 0.8230243166908622
color:
  brandStrength: 0.09023964102379978
  lightness: 0.9871418997645378
  saturation: 0.10205604787915945
  rhythmicContrast: 0.24716458399780095
  brandColors:
    - '#6B0C22'
    - '#D9042B'
    - '#F4CB89'
    - '#588C8C'
    - '#011C26'
author:
  name: Steven Guinter
  email: saguinter@gmail.com
name: Harrisburg Police Athletic League
navigation:
  - name: About
    url: 'https://hbgpal.wordpress.com/about/'
    type: external
  - name: Become a Member
    id: 737eb1d4-2562-4941-856d-ab25870591b9
    type: content
  - name: Programs
    url: 'https://hbgpal.wordpress.com/programs/'
    type: external
  - name: Support
    url: 'https://hbgpal.wordpress.com/support/'
    type: external
  - name: Contact Us
    url: 'https://hbgpal.wordpress.com/contact-us/'
    type: external
  - name: Community
    url: 'https://hbgpal.wordpress.com/hbgcommunity/'
    type: external
  - name: Forms
    url: 'https://hbgpal.wordpress.com/online-forms/'
    type: external
  - name: Follow
    url: 'https://hbgpal.wordpress.com/about/follow-pal/'
    type: external
title: Programs
description: We are Harrisburg PAL on "thegrid"
